### ISSUE TITLE
What are the requirements to run the program?

### ISSUE THREAD

**Issue by shashi4u** [subhrajyotidasgupta/cardiogan#1]
@subhrajyotidasgupta
Can you provide information on the dependencies to run the program?
Such as:

Python Version
Tensorflow Version
Attention class implementation

Also can you provide a small snippet of training data "data.csv" and what each column in the csv represent?

Thanks

**Comment by subhrajyotidasgupta** [comment]
Hey.

Was caught up and couldn't update the remaining files. It'll take some time to clean the code and update. Also, the publication details will be up soon.

However, the standard versions of Python 3+ and Tf 2+ would work. Additionally, the Attention module can be easily implemented using the official Tf docs on the Attention layer and customising for the ECGs. [Ref. [1 ](https://www.tensorflow.org/api_docs/python/tf/keras/layers/Attention) and [2](https://www.tensorflow.org/tutorials/text/image_captioning#model)]

The dataset is `MIT BIH Arrhythmia Database`.
